# ================================================================
#   CANON + SCALA NGENIX FINDER
#   Версия 3.9.1 — Высокопроизводительный валидатор HLS-потоков
# ================================================================

import time
import re
from typing import Dict, Tuple, Any, List
from concurrent.futures import ThreadPoolExecutor, as_completed

try:
    import requests
except ImportError:
    requests = None


# -------------------------------
# Единый словарь сопоставления (CHANNEL_META)
# -------------------------------

CHANNEL_META = {
    #  ФЕДЕРАЛЬНЫЕ
    "perviy": ("Первый канал", "Федеральные"),
    "rossiya_1": ("Россия 1", "Федеральные"),
    "match_tv": ("Матч ТВ", "Федеральные"),
    "ntv": ("НТВ", "Федеральные"),
    "pyatyi": ("Пятый канал", "Федеральные"),
    "rossiya_k": ("Россия К", "Федеральные"),
    "rossiya_24": ("Россия 24", "Федеральные"),
    "karusel": ("Карусель", "Федеральные"),
    "otr": ("ОТР", "Федеральные"),
    "tvc": ("ТВ Центр", "Федеральные"),
    "rentv": ("РЕН ТВ", "Федеральные"),
    "spas": ("Спас", "Федеральные"),
    "sts": ("СТС", "Федеральные"),
    "domashniy": ("Домашний", "Федеральные"),
    "tv3": ("ТВ-3", "Федеральные"),
    "pyatnica": ("Пятница!", "Федеральные"),
    "zvezda": ("Звезда", "Федеральные"),
    "mir": ("Мир", "Федеральные"),
    "tnt": ("ТНТ", "Федеральные"),
    "muz_tv": ("Муз-ТВ", "Федеральные"),

    #  ПРИРОДА / WILDLIFE / TRAVEL / SCIENCE
    "wild_nature": ("Wild Nature", "Природа"),
    "nature_hd": ("Nature HD", "Природа"),
    "planet_earth_hd": ("Planet Earth HD", "Природа"),
    "wildlife_tv": ("Wildlife TV", "Природа"),
    "ocean_tv": ("Ocean TV", "Природа"),
    "zhivaya_planeta": ("Живая Планета", "Природа"),
    "moya_planeta": ("Моя Планета", "Природа"),
    "nauka": ("Наука", "Природа"),
    "techno_24": ("Techno 24", "Природа"),
    "travelxp": ("TravelXP", "Природа"),
    "travel_plus": ("Travel+", "Природа"),
    "natgeo": ("National Geographic", "Природа"),
    "natgeo_wild": ("NatGeo Wild", "Природа"),
    "discovery_channel": ("Discovery Channel", "Природа"),
    "discovery_science": ("Discovery Science", "Природа"),
    "discovery_turbo": ("Discovery Turbo", "Природа"),
    "discovery_world": ("Discovery World", "Природа"),
    "animal_planet": ("Animal Planet", "Природа"),
    "history_channel": ("History Channel", "Природа"),
    "viasat_nature": ("Viasat Nature", "Природа"),
    "viasat_explore": ("Viasat Explore", "Природа"),
    "viasat_history": ("Viasat History", "Природа"),
    "travel_channel": ("Travel Channel", "Природа"),
    "hgtv": ("HGTV", "Природа"),
    "fine_living": ("Fine Living", "Природа"),
    "myzen": ("MyZen TV", "Природа"),

    #  TV1000 — ВСЯ ЛИНЕЙКА
    "tv1000": ("TV1000", "Кино"),
    "tv1000_action": ("TV1000 Action", "Кино"),
    "tv1000_russian": ("TV1000 Русское кино", "Кино"),
    "tv1000_world": ("TV1000 World", "Кино"),
    "tv1000_premium": ("TV1000 Premium", "Кино"),
    "tv1000_thriller": ("TV1000 Thriller", "Кино"),
    "tv1000_dark": ("TV1000 Dark", "Кино"),
    "tv1000_horror": ("TV1000 Horror", "Кино"),
    "tv1000_comedy": ("TV1000 Comedy", "Кино"),
    "tv1000_family": ("TV1000 Family", "Кино"),
    "tv1000_romance": ("TV1000 Romance", "Кино"),
    "tv1000_adventure": ("TV1000 Adventure", "Кино"),
    "tv1000_classic": ("TV1000 Classic", "Кино"),
    "tv1000_megahit": ("TV1000 Megahit", "Кино"),
    "tv1000_premiere": ("TV1000 Premiere", "Кино"),
    "tv1000_serial": ("TV1000 Serial", "Кино"),
    "tv1000_hd": ("TV1000 HD", "Кино"),
    "tv1000_plus": ("TV1000+", "Кино"),

    #  ДЕТСКИЕ КАНАЛЫ
    "ani": ("Ani", "Детские"),
    "tlum_hd": ("Tlum HD", "Детские"),
    "mult": ("Мульт", "Детские"),
    "mult_music": ("Мульт Музыка", "Детские"),
    "sts_kids": ("СТС Kids", "Детские"),
    "tiji": ("TiJi", "Детские"),
    "gulli": ("Gulli", "Детские"),
    "cartoon_network": ("Cartoon Network", "Детские"),
    "boomerang": ("Boomerang", "Детские"),
    "nickelodeon": ("Nickelodeon", "Детские"),
    "nick_jr": ("Nick Jr", "Детские"),
    "nickelodeon_hd": ("Nickelodeon HD", "Детские"),
    "nicktoons": ("NickToons", "Детские"),
    "disney": ("Disney Channel", "Детские"),
    "baby_tv": ("Baby TV", "Детские"),
    "jimjam": ("JimJam", "Детские"),
    "duck_tv": ("Duck TV", "Детские"),
    "fixiki": ("Фиксики", "Детские"),
    "kids_time": ("Kids Time", "Детские"),
    "kids_co": ("KidsCo", "Детские"),
    "minimax": ("Minimax", "Детские"),
    "panda_tv": ("Panda TV", "Детские"),
    "happy_kids": ("Happy Kids", "Детские"),
    "junior_music": ("Junior Music", "Детские"),
    "cartoonito": ("Cartoonito", "Детские"),
    "super_wings": ("Super Wings TV", "Детские"),
    "lego_tv": ("LEGO TV", "Детские"),
    "animax": ("Animax", "Детские"),
    "pogo": ("Pogo", "Детские"),
    "hungama": ("Hungama", "Детские"),

    #  СПОРТИВНЫЕ КАНАЛЫ
    "match_arena": ("Матч! Арена", "Спорт"),
    "match_igra": ("Матч! Игра", "Спорт"),
    "match_boec": ("Матч! Боец", "Спорт"),
    "match_strana": ("Матч! Страна", "Спорт"),
    "match_planeta": ("Матч! Планета", "Спорт"),
    "match_premier": ("Матч! Премьер", "Спорт"),
    "match_futbol_1": ("Матч! Футбол 1", "Спорт"),
    "match_futbol_2": ("Матч! Футбол 2", "Спорт"),
    "match_futbol_3": ("Матч! Футбол 3", "Спорт"),
    "khl": ("КХЛ", "Спорт"),
    "khl_prime": ("КХЛ Prime", "Спорт"),
    "khl_world": ("КХЛ World", "Спорт"),
    "start": ("Старт", "Спорт"),
    "start_basket": ("Старт Баскет", "Спорт"),
    "start_triumf": ("Старт Триумф", "Спорт"),
    "start_hockey": ("Старт Хоккей", "Спорт"),
    "udar": ("Удар", "Спорт"),
    "boxtv": ("Бокс ТВ", "Спорт"),
    "ufc_channel": ("UFC Channel", "Спорт"),
    "fightbox": ("FightBox", "Спорт"),
    "mma_tv": ("MMA TV", "Спорт"),
    "wbc_fight": ("WBC Fight", "Спорт"),
    "eurosport_1": ("Eurosport 1", "Спорт"),
    "eurosport_2": ("Eurosport 2", "Спорт"),
    "fastnfunbox": ("Fast&FunBox", "Спорт"),
    "extreme_sports": ("Extreme Sports", "Спорт"),
    "xsport": ("XSport", "Спорт"),
    "fuel_tv": ("Fuel TV", "Спорт"),
    "trace_sport_stars": ("Trace Sport Stars", "Спорт"),
    "premier_league_tv": ("Premier League TV", "Спорт"),
    "laliga_tv": ("LaLiga TV", "Спорт"),
    "bundesliga_tv": ("Bundesliga TV", "Спорт"),
    "serie_a_tv": ("Serie A TV", "Спорт"),
    "liga_tv": ("Liga TV", "Спорт"),
    "motorsport_tv": ("Motorsport TV", "Спорт"),
    "nascar_tv": ("NASCAR TV", "Спорт"),
    "f1_tv": ("Formula 1 TV", "Спорт"),
    "fifa_tv": ("FIFA TV", "Спорт"),
    "nhl_tv": ("NHL TV", "Спорт"),
    "nba_tv": ("NBA TV", "Спорт"),
    "nfl_tv": ("NFL TV", "Спорт"),
    "sport_plus": ("Спорт Плюс", "Спорт"),
    "sport_hd": ("Спорт HD", "Спорт"),
    "sport_mania": ("Sport Mania", "Спорт"),
    "sport_1": ("Sport 1", "Спорт"),
    "sport_2": ("Sport 2", "Спорт"),
    "sport_3": ("Sport 3", "Спорт"),
    "fight_sports": ("Fight Sports", "Спорт"),
    "boxing_world": ("Boxing World", "Спорт"),
    "hockey_world": ("Hockey World", "Спорт"),
    "football_world": ("Football World", "Спорт"),

    #  КИНОКАНАЛЫ
    "amedia_1": ("Amedia 1", "Кино"),
    "amedia_2": ("Amedia 2", "Кино"),
    "amedia_premium_hd": ("Amedia Premium HD", "Кино"),
    "amedia_hit": ("Amedia Hit", "Кино"),
    "filmbox": ("FilmBox", "Кино"),
    "filmbox_arthouse": ("FilmBox Arthouse", "Кино"),
    "filmbox_action": ("FilmBox Action", "Кино"),
    "filmbox_family": ("FilmBox Family", "Кино"),
    "filmbox_plus": ("FilmBox Plus", "Кино"),
    "viju_comedy": ("Viju Comedy", "Кино"),
    "viju_megahit": ("Viju Megahit", "Кино"),
    "viju_premiere": ("Viju Premiere", "Кино"),
    "viju_serial": ("Viju Serial", "Кино"),
    "viju_thriller": ("Viju Thriller", "Кино"),
    "viju_dark": ("Viju Dark", "Кино"),
    "viju_horror": ("Viju Horror", "Кино"),
    "amc": ("AMC", "Кино"),
    "amc_thriller": ("AMC Thriller", "Кино"),
    "amc_fear": ("AMC Fear", "Кино"),
    "hollywood_hd": ("Hollywood HD", "Кино"),
    "hollywood_classic": ("Hollywood Classic", "Кино"),
    "dom_kino": ("Дом Кино", "Кино"),
    "dom_kino_premium_hd": ("Дом Кино Премиум HD", "Кино"),
    "evrokino": ("Еврокино", "Кино"),
    "illusion_plus": ("Иллюзион+", "Кино"),
    "mir_seriala": ("Мир сериала", "Кино"),
    "tv_xxi": ("ТВ XXI", "Кино"),
    "365_dney_tv": ("365 дней ТВ", "Кино"),
    "galaxy": ("Galaxy", "Кино"),
    "kino_tv": ("Кино ТВ", "Кино"),
    "kinomix": ("Киномикс", "Кино"),
    "kinohit": ("Кинохит", "Кино"),
    "kinopokaz": ("Кинопоказ", "Кино"),
    "start_megahit": ("Start Megahit", "Кино"),
    "start_premiere": ("Start Premiere", "Кино"),
    "start_serial": ("Start Serial", "Кино"),
    "paramount_channel": ("Paramount Channel", "Кино"),
    "paramount_comedy": ("Paramount Comedy", "Кино"),
    "sony_channel": ("Sony Channel", "Кино"),
    "sony_turbo": ("Sony Turbo", "Кино"),
    "universal_channel": ("Universal Channel", "Кино"),
    "axn": ("AXN", "Кино"),
    "syfy": ("SyFy", "Кино"),
    "epic_drama": ("Epic Drama", "Кино"),
    "kino_1": ("Кино 1", "Кино"),
    "kino_2": ("Кино 2", "Кино"),
    "kino_3": ("Кино 3", "Кино"),
    "kino_premium": ("Кино Премиум", "Кино"),
    "kino_platinum": ("Кино Платинум", "Кино"),
    "kino_family": ("Кино Семейный", "Кино"),
    "kino_comedy": ("Кино Комедия", "Кино"),
    "kino_action": ("Кино Экшен", "Кино"),
    "kino_thriller": ("Кино Триллер", "Кино"),
    "kino_romance": ("Кино Роман", "Кино"),
    "kino_adventure": ("Кино Приключения", "Кино"),
    "kino_classic": ("Кино Классика", "Кино"),
    "axn_black": ("AXN Black", "Кино"),
    "axn_white": ("AXN White", "Кино"),
    "tcm": ("TCM", "Кино"),
    "amc_movies": ("AMC Movies", "Кино"),
    "mgm": ("MGM Channel", "Кино"),
    "warner_tv": ("Warner TV", "Кино"),
    "hbo": ("HBO", "Кино"),
    "hbo_2": ("HBO 2", "Кино"),
    "hbo_3": ("HBO 3", "Кино"),

    #  УЖАСЫ / ТРИЛЛЕРЫ / МИСТИКА
    "nst": ("НСТ — Настоящее Страшное Телевидение", "Ужасы"),
    "kinoujas": ("Киноужас", "Ужасы"),
    "kinomystic": ("Киномистика", "Ужасы"),
    "kinoterrory": ("Кино Террор", "Ужасы"),
    "dark_tv": ("Dark TV", "Ужасы"),
    "horror_tv": ("Horror TV", "Ужасы"),
    "trash_horror": ("Trash Horror", "Ужасы"),
    "scream_horror": ("Scream Horror", "Ужасы"),
    "cult_horror": ("Cult Horror", "Ужасы"),
    "indie_horror": ("Indie Horror", "Ужасы"),
    "dark_cinema": ("Dark Cinema", "Ужасы"),
    "mystic_tv": ("Mystic TV", "Ужасы"),
    "thriller_tv": ("Thriller TV", "Ужасы"),
    "thriller_box": ("Thriller Box", "Ужасы"),
    "crime_thriller": ("Crime Thriller", "Ужасы"),
    "amc_dark": ("AMC Dark", "Ужасы"),
    "fox_crime": ("Fox Crime", "Ужасы"),
    "fox_thriller": ("Fox Thriller", "Ужасы"),
    "fear_channel": ("Fear Channel", "Ужасы"),
    "terror_tv": ("Terror TV", "Ужасы"),
    "horror_box": ("Horror Box", "Ужасы"),
    "nightmare_tv": ("Nightmare TV", "Ужасы"),
    "blood_tv": ("Blood TV", "Ужасы"),
    "shadow_tv": ("Shadow TV", "Ужасы"),
    "phantom_tv": ("Phantom TV", "Ужасы"),
    "paranormal_tv": ("Paranormal TV", "Ужасы"),
    "mystery_tv": ("Mystery TV", "Ужасы"),
    "occult_tv": ("Occult TV", "Ужасы"),
    "ghost_tv": ("Ghost TV", "Ужасы"),
    "supernatural_tv": ("Supernatural TV", "Ужасы"),
    "horror_plus": ("Horror+", "Ужасы"),
    "thriller_plus": ("Thriller+", "Ужасы"),
    "dark_plus": ("Dark+", "Ужасы"),
    "mystic_plus": ("Mystic+", "Ужасы"),
    "fear_plus": ("Fear+", "Ужасы"),

    #  ПОЗНАВАТЕЛЬНЫЕ / ДОКУМЕНТАЛЬНЫЕ
    "discovery_id": ("Investigation Discovery", "Познавательные"),
    "discovery_civilization": ("Discovery Civilization", "Познавательные"),
    "history_2": ("History 2", "Познавательные"),
    "docubox": ("DocuBox", "Познавательные"),
    "fashionbox": ("FashionBox", "Познавательные"),
    "nostalgia": ("Ностальгия", "Познавательные"),
    "hunterfisher": ("Охотник и рыболов", "Познавательные"),
    "rybolov": ("Рыболов", "Познавательные"),
    "oruzhie": ("Оружие", "Познавательные"),
    "hunt_world": ("Hunt World", "Познавательные"),
    "fish_world": ("Fish World", "Познавательные"),
    "da_vinci": ("Da Vinci", "Познавательные"),
    "science_360": ("Science 360", "Познавательные"),
    "world_documentary": ("World Documentary", "Познавательные"),
    "geo_tv": ("GEO TV", "Познавательные"),
    "explorer_tv": ("Explorer TV", "Познавательные"),
    "adventure_tv": ("Adventure TV", "Познавательные"),
    "planet_hd": ("Planet HD", "Познавательные"),
    "earth_hd": ("Earth HD", "Познавательные"),
    "wild_hd": ("Wild HD", "Познавательные"),
    "space_tv": ("Space TV", "Познавательные"),
    "universe_tv": ("Universe TV", "Познавательные"),

    #  КУЛИНАРИЯ / ЕДА
    "eda": ("Еда", "Кулинария"),
    "eda_hd": ("Еда HD", "Кулинария"),
    "kitchen_tv": ("Kitchen TV", "Кулинария"),
    "chef_tv": ("Chef TV", "Кулинария"),
    "my_cuisine": ("Моя Кухня", "Кулинария"),
    "kulinarnyi": ("Кулинарный", "Кулинария"),
    "kulinaria_hd": ("Кулинария HD", "Кулинария"),
    "food_network": ("Food Network", "Кулинария"),
    "gusto_tv": ("Gusto TV", "Кулинария"),
    "bon_appetit": ("Bon Appétit TV", "Кулинария"),
    "hgtv_food": ("HGTV Food", "Кулинария"),
    "viju_cooking": ("Viju Cooking", "Кулинария"),
    "viju_food": ("Viju Food", "Кулинария"),
    "cook_tv": ("Cook TV", "Кулинария"),
    "cook_hd": ("Cook HD", "Кулинария"),
    "chef_plus": ("Chef+", "Кулинария"),
    "kitchen_plus": ("Kitchen+", "Кулинария"),
    "taste_tv": ("Taste TV", "Кулинария"),
    "world_cuisine": ("World Cuisine", "Кулинария"),
    "gourmet_tv": ("Gourmet TV", "Кулинария"),
    "culinary_world": ("Culinary World", "Кулинария"),
    "sweet_tv": ("Sweet TV", "Кулинария"),
    "dessert_tv": ("Dessert TV", "Кулинария"),
    "baking_tv": ("Baking TV", "Кулинария"),
    "grill_tv": ("Grill TV", "Кулинария"),
    "bbq_tv": ("BBQ TV", "Кулинария"),
    "vegan_tv": ("Vegan TV", "Кулинария"),
    "healthy_food_tv": ("Healthy Food TV", "Кулинария"),

    #  МУЗЫКАЛЬНЫЕ КАНАЛЫ
    "bridge_tv": ("Bridge TV", "Музыка"),
    "bridge_hits": ("Bridge Hits", "Музыка"),
    "bridge_deluxe": ("Bridge Deluxe", "Музыка"),
    "bridge_classic": ("Bridge Classic", "Музыка"),
    "bridge_fresh": ("Bridge Fresh", "Музыка"),
    "mtv": ("MTV", "Музыка"),
    "mtv_live_hd": ("MTV Live HD", "Музыка"),
    "mtv_hits": ("MTV Hits", "Музыка"),
    "mtv_rocks": ("MTV Rocks", "Музыка"),
    "mtv_dance": ("MTV Dance", "Музыка"),
    "vh1": ("VH1", "Музыка"),
    "vh1_classic": ("VH1 Classic", "Музыка"),
    "mezzo": ("Mezzo", "Музыка"),
    "mezzo_live_hd": ("Mezzo Live HD", "Музыка"),
    "mezzo_classic": ("Mezzo Classic", "Музыка"),
    "russian_music_box": ("Russian Music Box", "Музыка"),
    "music_box_ru": ("Music Box Russia", "Музыка"),
    "music_box_hd": ("Music Box HD", "Музыка"),
    "music_box_ua": ("Music Box UA", "Музыка"),
    "europa_plus_tv": ("Europa Plus TV", "Музыка"),
    "music_first": ("Музыка Первого", "Музыка"),
    "soyuz": ("Союз", "Музыка"),
    "rutv": ("RU.TV", "Музыка"),
    "tnt_music": ("ТНТ Music", "Музыка"),
    "sts_love_music": ("СТС Love Music", "Музыка"),
    "zhara_tv": ("Жара ТВ", "Музыка"),
    "trace_urban": ("Trace Urban", "Музыка"),
    "trace_latin": ("Trace Latin", "Музыка"),
    "trace_africa": ("Trace Africa", "Музыка"),
    "trace_tropical": ("Trace Tropical", "Музыка"),
    "deluxe_music": ("Deluxe Music", "Музыка"),
    "unitv": ("UniTV", "Музыка"),
    "4fun_tv": ("4Fun TV", "Музыка"),
    "clubland_tv": ("Clubland TV", "Музыка"),
    "dance_tv": ("Dance TV", "Музыка"),
    "party_tv": ("Party TV", "Музыка"),
    "hit_tv": ("Hit TV", "Музыка"),
    "top_music": ("Top Music", "Музыка"),
    "global_music": ("Global Music", "Музыка"),
    "music_plus": ("Music+", "Музыка"),
    "music_360": ("Music 360", "Музыка"),
    "retro_music": ("Retro Music", "Музыка"),
    "classic_music": ("Classic Music", "Музыка"),
    "jazz_tv": ("Jazz TV", "Музыка"),
    "rock_tv": ("Rock TV", "Музыка"),
    "metal_tv": ("Metal TV", "Музыка"),
    "hiphop_tv": ("HipHop TV", "Музыка"),
    "rap_tv": ("Rap TV", "Музыка"),
    "pop_tv": ("Pop TV", "Музыка"),
    "kpop_tv": ("K‑Pop TV", "Музыка"),
    "edm_tv": ("EDM TV", "Музыка"),

    #  РЕГИОНАЛЬНЫЕ КАНАЛЫ РОССИИ
    "moskva_24": ("Москва 24", "Региональные"),
    "moskva_doverie": ("Москва Доверие", "Региональные"),
    "moskva_1": ("Москва 1", "Региональные"),
    "tvcentr_moscow": ("ТВ Центр Москва", "Региональные"),
    "peterburg_5": ("Санкт-Петербург 5", "Региональные"),
    "peterburg_78": ("78 канал", "Региональные"),
    "peterburg_otv": ("ОТВ Петербург", "Региональные"),
    "peterburg_len_tv": ("Лен ТВ", "Региональные"),
    "360": ("360 Подмосковье", "Региональные"),
    "chekhov_tv": ("Чехов ТВ", "Региональные"),
    "balashikha_tv": ("Балашиха ТВ", "Региональные"),
    "korolev_tv": ("Королёв ТВ", "Региональные"),
    "len_obl_tv": ("ЛенОбл ТВ", "Региональные"),
    "vsevolozhsk_tv": ("Всеволожск ТВ", "Региональные"),
    "tatarstan_tv": ("Татарстан ТВ", "Региональные"),
    "tnv": ("ТНВ", "Региональные"),
    "tnv_planeta": ("ТНВ Планета", "Региональные"),
    "kazan_first": ("Первый Казанский", "Региональные"),
    "bashkortostan_tv": ("Башкортостан ТВ", "Региональные"),
    "bst": ("БСТ", "Региональные"),
    "ufa_tv": ("Уфа ТВ", "Региональные"),
    "krasnodar_tv": ("Краснодар ТВ", "Региональные"),
    "kuban_24": ("Кубань 24", "Региональные"),
    "sochi_tv": ("Сочи ТВ", "Региональные"),
    "ekb_tv": ("Екатеринбург ТВ", "Региональные"),
    "ekb_4": ("4 канал Екатеринбург", "Региональные"),
    "ekb_otv": ("ОТВ Екатеринбург", "Региональные"),
    "novosibirsk_tv": ("Новосибирск ТВ", "Региональные"),
    "nsk_otv": ("ОТВ Новосибирск", "Региональные"),
    "samara_tv": ("Самара ТВ", "Региональные"),
    "samara_guberniya": ("Губерния Самара", "Региональные"),
    "perm_tv": ("Пермь ТВ", "Региональные"),
    "rifei_perm": ("Рифей Пермь", "Региональные"),
    "omsk_tv": ("Омск ТВ", "Региональные"),
    "omsk_12": ("12 канал Омск", "Региональные"),
    "tomsk_tv": ("Томск ТВ", "Региональные"),
    "tomsk_vest": ("Вести Томск", "Региональные"),
    "volgograd_tv": ("Волгоград ТВ", "Региональные"),
    "volgograd_1": ("Первый Волгоградский", "Региональные"),
    "vladivostok_tv": ("Владивосток ТВ", "Региональные"),
    "primorye_tv": ("Приморье ТВ", "Региональные"),
    "kaliningrad_tv": ("Калининград ТВ", "Региональные"),
    "balt_tv": ("Балтик ТВ", "Региональные"),
    "west_tv": ("Запад ТВ", "Региональные"),
    "kaliningrad_1": ("Первый Калининградский", "Региональные"),
    "chelyabinsk_tv": ("Челябинск ТВ", "Региональные"),
    "cheltv_31": ("31 канал Челябинск", "Региональные"),
    "irkutsk_tv": ("Иркутск ТВ", "Региональные"),
    "irkutsk_as_baikal": ("АС Байкал ТВ", "Региональные"),
    "khabarovsk_tv": ("Хабаровск ТВ", "Региональные"),
    "dv_tv": ("ДВ ТВ", "Региональные"),
    "yakutia_tv": ("Якутия 24", "Региональные"),
    "sakha_tv": ("Саха ТВ", "Региональные"),
    "karelia_tv": ("Карелия ТВ", "Региональные"),
    "ptz_tv": ("Петрозаводск ТВ", "Региональные"),
    "komi_tv": ("Коми ТВ", "Региональные"),
    "siktivkar_tv": ("Сыктывкар ТВ", "Региональные"),
    "mordovia_tv": ("Мордовия ТВ", "Региональные"),
    "mariel_tv": ("Марий Эл ТВ", "Региональные"),
    "udmurtia_tv": ("Удмуртия ТВ", "Региональные"),
    "chuvashia_tv": ("Чувашия ТВ", "Региональные"),
    "altai_tv": ("Алтай ТВ", "Региональные"),
    "barnaul_tv": ("Барнаул ТВ", "Региональные"),
    "kemerovo_tv": ("Кемерово ТВ", "Региональные"),
    "kuzbass_tv": ("Кузбасс ТВ", "Региональные"),
    "tyumen_tv": ("Тюмень ТВ", "Региональные"),
    "region_tyumen": ("Регион-Тюмень", "Региональные"),
    "otr_region": ("ОТР Регион", "Региональные"),
    "otr_local": ("ОТР Локальный", "Региональные"),
    "tvc_region": ("ТВЦ Регион", "Региональные"),
    "tvc_local": ("ТВЦ Локальный", "Региональные"),
    "city_tv": ("City TV", "Региональные"),
    "gorod_tv": ("Город ТВ", "Региональные"),
    "local_tv": ("Local TV", "Региональные"),
    "municipal_tv": ("Муниципальный ТВ", "Ре