name: IPTV Auto Builder

on:
  schedule:
    # Запуск каждые 12 часов (в 00:00 и 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Кнопка для ручного запуска во вкладке Actions на GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение репозитория GitHub
        uses: actions/checkout@v4

      - name: Настройка среды Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Сборка плейлиста из GitVerse
        run: python main.py

      - name: Автоматический коммит обновленного playlist.m3u
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add playlist.m3u
          git diff-index --quiet HEAD || git commit -m "Auto-update and sort playlist.m3u [skip ci]"
          git push
