name: VladPL_ngenixConvert

on:
  schedule:
    # Автоматический запуск каждые 6 часов (по UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Позволяет запускать процесс вручную из вкладки Actions

jobs:
  build-and-update:
    name: Обработка и обновление плейлиста
    runs-on: ubuntu-latest

    permissions:
      contents: write # Права на запись и запуск push в репозиторий

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка среды Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Скачивание скрипта конвертации
        run: |
          curl -sSL "https://raw.githubusercontent.com/Phoenix89S/IpTV_playlist_2026Ru/main/vladPl_ngenix.py" -o vladPl_ngenix.py

      - name: Запуск конвертации плейлиста
        run: python vladPl_ngenix.py

      - name: Сохранение и отправка изменений в репозиторий
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          # Индексируем сгенерированные файлы плейлистов
          git add *.m3u* || git add .
          
          # Проверяем, есть ли изменения перед фиксированием комита
          if git diff --staged --quiet; then
            echo "Изменений в плейлисте нет. Пропускаем фиксацию."
          else
            git commit -m "Автоматическое обновление плейлиста через VladPL_ngenixConvert [skip ci]"
            git push
          fi
